// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bookingMeating.proto

package bookingMeating;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bookingMeating.Empty)
    com.google.protobuf.MessageOrBuilder {
}
