// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: workManagement.proto

package workManagement;

public interface AssignTasksRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:workManagement.AssignTasksRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string requestMessage = 1;</code>
   */
  java.lang.String getRequestMessage();
  /**
   * <code>string requestMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestMessageBytes();
}
