// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: workManagement.proto

package workManagement;

public interface AssignTasksResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:workManagement.AssignTasksResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responseMessage = 1;</code>
   */
  java.lang.String getResponseMessage();
  /**
   * <code>string responseMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseMessageBytes();

  /**
   * <code>int32 responseCode = 2;</code>
   */
  int getResponseCode();
}
