// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bookingMeating.proto

package bookingMeating;

public final class bookingMeatingImpl {
  private bookingMeatingImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bookingMeating_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bookingMeating_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bookingMeating_LoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bookingMeating_LoginResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bookingMeating_MeatingRoomRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bookingMeating_MeatingRoomRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bookingMeating_MeatingRoomResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bookingMeating_MeatingRoomResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bookingMeating_LogoutRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bookingMeating_LogoutRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bookingMeating_LogoutResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bookingMeating_LogoutResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bookingMeating_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bookingMeating_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024bookingMeating.proto\022\016bookingMeating\"2" +
      "\n\014LoginRequest\022\020\n\010username\030\001 \001(\t\022\020\n\010pass" +
      "word\030\002 \001(\t\">\n\rLoginResponse\022\027\n\017responseM" +
      "essage\030\001 \001(\t\022\024\n\014responseCode\030\002 \001(\005\".\n\022Me" +
      "atingRoomRequest\022\030\n\020roomAvailability\030\001 \001" +
      "(\t\"D\n\023MeatingRoomResponse\022\027\n\017responseMes" +
      "sage\030\001 \001(\t\022\024\n\014responseCode\030\002 \001(\005\"!\n\rLogo" +
      "utRequest\022\020\n\010username\030\001 \001(\t\"?\n\016LogoutRes" +
      "ponse\022\027\n\017responseMessage\030\001 \001(\t\022\024\n\014respon" +
      "seCode\030\002 \001(\005\"\007\n\005Empty2\377\001\n\016bookingMeating" +
      "\022F\n\005login\022\034.bookingMeating.LoginRequest\032" +
      "\035.bookingMeating.LoginResponse\"\000\022Z\n\013meat" +
      "ingRoom\022\".bookingMeating.MeatingRoomRequ" +
      "est\032#.bookingMeating.MeatingRoomResponse" +
      "\"\0000\001\022I\n\006logout\022\035.bookingMeating.LogoutRe" +
      "quest\032\036.bookingMeating.LogoutResponse\"\000B" +
      "&\n\016bookingMeatingB\022bookingMeatingImplP\001b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_bookingMeating_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bookingMeating_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bookingMeating_LoginRequest_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_bookingMeating_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_bookingMeating_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bookingMeating_LoginResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", "ResponseCode", });
    internal_static_bookingMeating_MeatingRoomRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_bookingMeating_MeatingRoomRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bookingMeating_MeatingRoomRequest_descriptor,
        new java.lang.String[] { "RoomAvailability", });
    internal_static_bookingMeating_MeatingRoomResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_bookingMeating_MeatingRoomResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bookingMeating_MeatingRoomResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", "ResponseCode", });
    internal_static_bookingMeating_LogoutRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_bookingMeating_LogoutRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bookingMeating_LogoutRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_bookingMeating_LogoutResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_bookingMeating_LogoutResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bookingMeating_LogoutResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", "ResponseCode", });
    internal_static_bookingMeating_Empty_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_bookingMeating_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bookingMeating_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
