// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: workManagement.proto

package workManagement;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:workManagement.Empty)
    com.google.protobuf.MessageOrBuilder {
}
