// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: workManagement.proto

package workManagement;

public interface LogoutRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:workManagement.LogoutRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
