// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bookingMeating.proto

package bookingMeating;

public interface MeatingRoomRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bookingMeating.MeatingRoomRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string roomAvailability = 1;</code>
   */
  java.lang.String getRoomAvailability();
  /**
   * <code>string roomAvailability = 1;</code>
   */
  com.google.protobuf.ByteString
      getRoomAvailabilityBytes();
}
