// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: workManagement.proto

package workManagement;

public final class workManagementImpl {
  private workManagementImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_workManagement_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_workManagement_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_workManagement_LoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_workManagement_LoginResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_workManagement_AssignTasksRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_workManagement_AssignTasksRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_workManagement_AssignTasksResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_workManagement_AssignTasksResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_workManagement_LogoutRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_workManagement_LogoutRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_workManagement_LogoutResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_workManagement_LogoutResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_workManagement_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_workManagement_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024workManagement.proto\022\016workManagement\"2" +
      "\n\014LoginRequest\022\020\n\010username\030\001 \001(\t\022\020\n\010pass" +
      "word\030\002 \001(\t\">\n\rLoginResponse\022\027\n\017responseM" +
      "essage\030\001 \001(\t\022\024\n\014responseCode\030\002 \001(\005\",\n\022As" +
      "signTasksRequest\022\026\n\016requestMessage\030\001 \001(\t" +
      "\"D\n\023AssignTasksResponse\022\027\n\017responseMessa" +
      "ge\030\001 \001(\t\022\024\n\014responseCode\030\002 \001(\005\"!\n\rLogout" +
      "Request\022\020\n\010username\030\001 \001(\t\"?\n\016LogoutRespo" +
      "nse\022\027\n\017responseMessage\030\001 \001(\t\022\024\n\014response" +
      "Code\030\002 \001(\005\"\007\n\005Empty2\201\002\n\016workManagement\022F" +
      "\n\005login\022\034.workManagement.LoginRequest\032\035." +
      "workManagement.LoginResponse\"\000\022\\\n\013assign" +
      "Tasks\022\".workManagement.AssignTasksReques" +
      "t\032#.workManagement.AssignTasksResponse\"\000" +
      "(\0010\001\022I\n\006logout\022\035.workManagement.LogoutRe" +
      "quest\032\036.workManagement.LogoutResponse\"\000B" +
      "&\n\016workManagementB\022workManagementImplP\001b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_workManagement_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_workManagement_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_workManagement_LoginRequest_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_workManagement_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_workManagement_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_workManagement_LoginResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", "ResponseCode", });
    internal_static_workManagement_AssignTasksRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_workManagement_AssignTasksRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_workManagement_AssignTasksRequest_descriptor,
        new java.lang.String[] { "RequestMessage", });
    internal_static_workManagement_AssignTasksResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_workManagement_AssignTasksResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_workManagement_AssignTasksResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", "ResponseCode", });
    internal_static_workManagement_LogoutRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_workManagement_LogoutRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_workManagement_LogoutRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_workManagement_LogoutResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_workManagement_LogoutResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_workManagement_LogoutResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", "ResponseCode", });
    internal_static_workManagement_Empty_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_workManagement_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_workManagement_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
