// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calendarMeating.proto

package calendarMeating;

public final class calendarMeatingImpl {
  private calendarMeatingImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calendarMeating_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_calendarMeating_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calendarMeating_LoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_calendarMeating_LoginResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calendarMeating_ScheduleMeatingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_calendarMeating_ScheduleMeatingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calendarMeating_ScheduleMeatingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_calendarMeating_ScheduleMeatingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calendarMeating_LogoutRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_calendarMeating_LogoutRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calendarMeating_LogoutResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_calendarMeating_LogoutResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025calendarMeating.proto\022\017calendarMeating" +
      "\"2\n\014LoginRequest\022\020\n\010username\030\001 \001(\t\022\020\n\010pa" +
      "ssword\030\002 \001(\t\">\n\rLoginResponse\022\027\n\017respons" +
      "eMessage\030\001 \001(\t\022\024\n\014responseCode\030\002 \001(\005\"*\n\026" +
      "ScheduleMeatingRequest\022\020\n\010username\030\001 \001(\t" +
      "\"H\n\027ScheduleMeatingResponse\022\027\n\017responseM" +
      "essage\030\001 \001(\t\022\024\n\014responseCode\030\002 \001(\005\"!\n\rLo" +
      "goutRequest\022\020\n\010username\030\001 \001(\t\"?\n\016LogoutR" +
      "esponse\022\027\n\017responseMessage\030\001 \001(\t\022\024\n\014resp" +
      "onseCode\030\002 \001(\0052\222\002\n\017calendarMeating\022H\n\005lo" +
      "gin\022\035.calendarMeating.LoginRequest\032\036.cal" +
      "endarMeating.LoginResponse\"\000\022h\n\017schedule" +
      "Meating\022\'.calendarMeating.ScheduleMeatin" +
      "gRequest\032(.calendarMeating.ScheduleMeati" +
      "ngResponse\"\000(\001\022K\n\006logout\022\036.calendarMeati" +
      "ng.LogoutRequest\032\037.calendarMeating.Logou" +
      "tResponse\"\000B(\n\017calendarMeatingB\023calendar" +
      "MeatingImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_calendarMeating_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_calendarMeating_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_calendarMeating_LoginRequest_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_calendarMeating_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_calendarMeating_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_calendarMeating_LoginResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", "ResponseCode", });
    internal_static_calendarMeating_ScheduleMeatingRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_calendarMeating_ScheduleMeatingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_calendarMeating_ScheduleMeatingRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_calendarMeating_ScheduleMeatingResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_calendarMeating_ScheduleMeatingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_calendarMeating_ScheduleMeatingResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", "ResponseCode", });
    internal_static_calendarMeating_LogoutRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_calendarMeating_LogoutRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_calendarMeating_LogoutRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_calendarMeating_LogoutResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_calendarMeating_LogoutResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_calendarMeating_LogoutResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", "ResponseCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
