// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calendarMeating.proto

package calendarMeating;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calendarMeating.Empty)
    com.google.protobuf.MessageOrBuilder {
}
