// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calendarMeating.proto

package calendarMeating;

/**
 * Protobuf type {@code calendarMeating.ScheduleMeatingRequest}
 */
public  final class ScheduleMeatingRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:calendarMeating.ScheduleMeatingRequest)
    ScheduleMeatingRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ScheduleMeatingRequest.newBuilder() to construct.
  private ScheduleMeatingRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ScheduleMeatingRequest() {
    requesteMessage_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ScheduleMeatingRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            requesteMessage_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return calendarMeating.calendarMeatingImpl.internal_static_calendarMeating_ScheduleMeatingRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return calendarMeating.calendarMeatingImpl.internal_static_calendarMeating_ScheduleMeatingRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            calendarMeating.ScheduleMeatingRequest.class, calendarMeating.ScheduleMeatingRequest.Builder.class);
  }

  public static final int REQUESTEMESSAGE_FIELD_NUMBER = 1;
  private volatile java.lang.Object requesteMessage_;
  /**
   * <code>string requesteMessage = 1;</code>
   */
  public java.lang.String getRequesteMessage() {
    java.lang.Object ref = requesteMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      requesteMessage_ = s;
      return s;
    }
  }
  /**
   * <code>string requesteMessage = 1;</code>
   */
  public com.google.protobuf.ByteString
      getRequesteMessageBytes() {
    java.lang.Object ref = requesteMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      requesteMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getRequesteMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requesteMessage_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getRequesteMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requesteMessage_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof calendarMeating.ScheduleMeatingRequest)) {
      return super.equals(obj);
    }
    calendarMeating.ScheduleMeatingRequest other = (calendarMeating.ScheduleMeatingRequest) obj;

    boolean result = true;
    result = result && getRequesteMessage()
        .equals(other.getRequesteMessage());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REQUESTEMESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getRequesteMessage().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static calendarMeating.ScheduleMeatingRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static calendarMeating.ScheduleMeatingRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static calendarMeating.ScheduleMeatingRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static calendarMeating.ScheduleMeatingRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static calendarMeating.ScheduleMeatingRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static calendarMeating.ScheduleMeatingRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static calendarMeating.ScheduleMeatingRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static calendarMeating.ScheduleMeatingRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static calendarMeating.ScheduleMeatingRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static calendarMeating.ScheduleMeatingRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static calendarMeating.ScheduleMeatingRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static calendarMeating.ScheduleMeatingRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(calendarMeating.ScheduleMeatingRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code calendarMeating.ScheduleMeatingRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:calendarMeating.ScheduleMeatingRequest)
      calendarMeating.ScheduleMeatingRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return calendarMeating.calendarMeatingImpl.internal_static_calendarMeating_ScheduleMeatingRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return calendarMeating.calendarMeatingImpl.internal_static_calendarMeating_ScheduleMeatingRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              calendarMeating.ScheduleMeatingRequest.class, calendarMeating.ScheduleMeatingRequest.Builder.class);
    }

    // Construct using calendarMeating.ScheduleMeatingRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      requesteMessage_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return calendarMeating.calendarMeatingImpl.internal_static_calendarMeating_ScheduleMeatingRequest_descriptor;
    }

    @java.lang.Override
    public calendarMeating.ScheduleMeatingRequest getDefaultInstanceForType() {
      return calendarMeating.ScheduleMeatingRequest.getDefaultInstance();
    }

    @java.lang.Override
    public calendarMeating.ScheduleMeatingRequest build() {
      calendarMeating.ScheduleMeatingRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public calendarMeating.ScheduleMeatingRequest buildPartial() {
      calendarMeating.ScheduleMeatingRequest result = new calendarMeating.ScheduleMeatingRequest(this);
      result.requesteMessage_ = requesteMessage_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof calendarMeating.ScheduleMeatingRequest) {
        return mergeFrom((calendarMeating.ScheduleMeatingRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(calendarMeating.ScheduleMeatingRequest other) {
      if (other == calendarMeating.ScheduleMeatingRequest.getDefaultInstance()) return this;
      if (!other.getRequesteMessage().isEmpty()) {
        requesteMessage_ = other.requesteMessage_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      calendarMeating.ScheduleMeatingRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (calendarMeating.ScheduleMeatingRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object requesteMessage_ = "";
    /**
     * <code>string requesteMessage = 1;</code>
     */
    public java.lang.String getRequesteMessage() {
      java.lang.Object ref = requesteMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requesteMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string requesteMessage = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRequesteMessageBytes() {
      java.lang.Object ref = requesteMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requesteMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string requesteMessage = 1;</code>
     */
    public Builder setRequesteMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      requesteMessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string requesteMessage = 1;</code>
     */
    public Builder clearRequesteMessage() {
      
      requesteMessage_ = getDefaultInstance().getRequesteMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string requesteMessage = 1;</code>
     */
    public Builder setRequesteMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      requesteMessage_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:calendarMeating.ScheduleMeatingRequest)
  }

  // @@protoc_insertion_point(class_scope:calendarMeating.ScheduleMeatingRequest)
  private static final calendarMeating.ScheduleMeatingRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new calendarMeating.ScheduleMeatingRequest();
  }

  public static calendarMeating.ScheduleMeatingRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ScheduleMeatingRequest>
      PARSER = new com.google.protobuf.AbstractParser<ScheduleMeatingRequest>() {
    @java.lang.Override
    public ScheduleMeatingRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ScheduleMeatingRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ScheduleMeatingRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ScheduleMeatingRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public calendarMeating.ScheduleMeatingRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

