// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calendarMeating.proto

package calendarMeating;

public interface ScheduleMeatingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calendarMeating.ScheduleMeatingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string requesteMessage = 1;</code>
   */
  java.lang.String getRequesteMessage();
  /**
   * <code>string requesteMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequesteMessageBytes();
}
